### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by kurt1984** [ekalinin/github-markdown-toc.go#2]
Mac OSX 10.11

$ wget https://github.com/ekalinin/github-markdown-toc.go/releases/download/0.4.0/gh-md-toc.linux.amd64.tgz
$ tar xzvf gh-md-toc.linux.amd64.tgz
x gh-md-toc
$ ./gh-md-toc --version
-bash: ./gh-md-toc: cannot execute binary file

**Comment by kurt1984** [comment]
I found that I should use mac version. Thanks!

**Comment by ekalinin** [comment]
No problem :)
