### ISSUE TITLE
Can't deal with the Remote files

### ISSUE THREAD

**Issue by yansheng836** [ekalinin/github-markdown-toc.go#20]
Just like this issue <https://github.com/ekalinin/github-markdown-toc.go/issues/13#issue-223321125>,it can't deal with the remote files.

For example,(the sample code in README.md)
```bash
$ ./gh-md-toc https://github.com/ekalinin/envirius/blob/master/README.md

Table of Contents
=================


Created by [gh-md-toc](https://github.com/ekalinin/github-markdown-toc.go)

```
My environment:
```bash
$ git --version
git version 2.21.0.windows.1

$ ./gh-md-toc --version
1.0.0

```

**Comment by ekalinin** [comment]
Hey,

Thanks for the report.

I have the same issue. As a workaround please, try this command (raw md, not html):

```
➜ ./gh-md-toc https://raw.githubusercontent.com/ekalinin/envirius/master/README.md
...
```

**Comment by yansheng836** [comment]
Thanks, it works. 

Maybe it's a good idea to add this way to the README.
