### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Ch00k** [ekalinin/github-markdown-toc.go#29]
@ekalinin could you please make a new release that would include the #24 fix?

**Comment by ekalinin** [comment]
Done:
- https://github.com/ekalinin/github-markdown-toc.go/releases/tag/1.2.0

**Comment by Ch00k** [comment]
Thanks for making the release, however I was expecting there to be pre-built binaries like in the previous release. I need to use a binary in a CI job, and I would like to avoid installing Go to build one myself.

**Comment by ekalinin** [comment]
> Thanks for making the release, however I was expecting there to be pre-built binaries like in the previous release. I need to use a binary in a CI job, and I would like to avoid installing Go to build one myself.

Ooops. Absolutely forgot.
Fixed :)

**Comment by LaundroMat** [comment]
Could you also add the Windows binaries? 🙏
