### ISSUE TITLE
[Feature] --insert flag

### ISSUE THREAD

**Issue by gedw99** [ekalinin/github-markdown-toc.go#33]
**Is your feature request related to a problem? Please describe.**

The none golang version has the ability to insert the generated TOC into the markdown file.

It would be nice if the golang tool also did that.

**Describe the solution you'd like**

Like so:

````

gh-md-toc --insert examples/02/README.md
gh-md-toc: error: unknown long flag '--insert', try --help

````

**Describe alternatives you've considered**

I could do it manually but well i am hoping this is something everyone might need.

**Additional context**

**Comment by ekalinin** [comment]
Hey,

Thanks for the report. It looks like we already have such an issue - #26
