### ISSUE TITLE
markdown-toc escaping chars in sections

### ISSUE THREAD

**Issue by iogf** [ekalinin/github-markdown-toc.go#4]
it seems it escapes chars like '-', '.' when in sections.

for example
- [The event-driven paradigm](#the-event-driven-paradigm)
- [Basic built-in handles](#basic-built-in-handles)
      \* [request.method](#requestmethod)
      \* [request.headers](#requestheaders)
      \* [request.data](#requestdata)
      \* [request.query](#requestquery)
      \* [request.path](#requestpath)

some editors have a way to navigate through markdown documents, vy uses the text between [title]  to navigate to sections in markdown docs. is possible to remove that behavior of escaping those chars from the toc?

**Comment by ekalinin** [comment]
Hey @iogf 

Thanks for the proposal.
Yeah, it seems, it's possible to add a special option for disabling the escaping.
