### ISSUE TITLE
[Question] Hi,it had worked correctly before, but do not work now and prompt such information. 

### ISSUE THREAD

**Issue by lewei50** [ekalinin/github-markdown-toc.go#40]
laoliu@anonemous:/mnt/c/Users/laoliu/Documents$ ./gh-md-toc tmp.md

Table of Contents
=================

Header: Vary=Accept
Header: Access-Control-Expose-Headers=ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
Header: Strict-Transport-Security=max-age=31536000; includeSubdomains; preload
Header: Referrer-Policy=origin-when-cross-origin, strict-origin-when-cross-origin
Header: Content-Type=text/html;charset=utf-8
Header: Cache-Control=public, max-age=60, s-maxage=60
Header: X-Frame-Options=deny
Header: X-Content-Type-Options=nosniff
Header: Etag=W/"8f02416ae1ffe52316586208420aa1472f865feba8e4f1a8ad86c2f4f78dd577"
Header: X-Ratelimit-Limit=60
Header: X-Github-Request-Id=27AF:64C2:4C8D70:4F9C04:637430A9
Header: X-Ratelimit-Reset=1668562617
Header: X-Ratelimit-Used=1
Header: X-Commonmarker-Version=0.23.6
Header: X-Github-Media-Type=github.v3; format=json
Header: X-Ratelimit-Remaining=59
Header: X-Ratelimit-Resource=core
Header: Access-Control-Allow-Origin=*
Header: X-Xss-Protection=0
Header: Server=GitHub.com
Header: Date=Wed, 16 Nov 2022 00:36:57 GMT
Header: Content-Security-Policy=default-src 'none'

Created by [gh-md-toc](https://github.com/ekalinin/github-markdown-toc.go)
laoliu@anonemous:/mnt/c/Users/laoliu/Documents$

**Comment by cgrindel** [comment]
Is your issue that the Table of Contents is not populating? If so, try out the fix in [this PR](https://github.com/ekalinin/github-markdown-toc.go/pull/38).

**Comment by ekalinin** [comment]
Hi, could you provide tmp.md's source?

Just tried with [README](https://github.com/ekalinin/github-markdown-toc.go/blob/master/README.md) of the current project and it worked well:

```
❯ go run cmd/gh-md-toc/main.go README.md

Table of Contents
=================

* [github\-markdown\-toc](#github-markdown-toc)
* [Table of Contents](#table-of-contents)
* [Installation](#installation)
  * [Precompiled binaries](#precompiled-binaries)
  * [Compiling from source](#compiling-from-source)
  * [Go Install](#go-install)
  * [Homebew (Mac only)](#homebew-mac-only)
* [Tests](#tests)
* [Usage](#usage)
  * [STDIN](#stdin)
  * [Local files](#local-files)
  * [Remote files](#remote-files)
  * [Multiple files](#multiple-files)
  * [Combo](#combo)
  * [Starting Depth](#starting-depth)
  * [Depth](#depth)
  * [No escape](#no-escape)
  * [Github token](#github-token)
  * [Bash/ZSH auto\-complete](#bashzsh-auto-complete)
* [Alpine Linux](#alpine-linux)
* [LICENSE](#license)

Created by [gh-md-toc](https://github.com/ekalinin/github-markdown-toc.go)

❯ go version
go version go1.19.4 darwin/arm64
```

**Comment by ekalinin** [comment]
Could you, please, try 1.2.1 version I just released:

https://github.com/ekalinin/github-markdown-toc.go/releases/tag/v1.2.1
